# Generated by Django 5.0.6 on 2024-06-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('Category', models.CharField(max_length=50)),
                ('Correct_Answer', models.TextField()),
                ('Wrong_Answer_1', models.CharField(max_length=50)),
                ('Wrong_Answer_2', models.CharField(max_length=50)),
                ('Wrong_Answer_3', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
